### ISSUE TITLE
Getting 'mode must be of type string' error while trying to run/watch simi-studio

### ISSUE THREAD

**Issue by shathish-vsk** [Simicart/simi-studio#1]
I have a Magento 2.3.0 instance running in my machine, when I build the simi-studio application (followed the instructions on this repo), the application was built with no errors. But when I tried to run/watch the simi-studio I get the following error.

Shathish:~/projects/magento/mage23/pwa-studio$ yarn run watch:simi-studio
yarn run v1.17.3
$ yarn workspace @simicart/simi-studio run watch; cd - >/dev/null
$ webpack-dev-server --progress --color --env.mode development
Using environment variables from .env
(node:17664) [ZOPFLI_COMPAT] MISSING_MODULE: Module "node-zopfli-es" was unavailable
Zopfli compression unavailable; will fall back to gzip.
BuildpackValidationError: ServiceWorkerPlugin: Invalid configuration object. ServiceWorkerPlugin was called with a configuration object that has the following problems:
	- mode must be of type string
    at Function.validateOptions (/home/local/RAGE/shathish.k/projects/magento/gear23/pwa-studio/packages/pwa-buildpack/lib/util/options-validator.js:43:15)
    at new ServiceWorkerPlugin (/home/local/RAGE/shathish.k/projects/magento/gear23/pwa-studio/packages/pwa-buildpack/lib/WebpackTools/plugins/ServiceWorkerPlugin.js:11:29)
    at module.exports (/home/local/RAGE/shathish.k/projects/magento/gear23/pwa-studio/packages/simi-studio/webpack.config.js:143:13)
Done in 2.15s.

Please advise.

**Comment by codynguyen1** [comment]
Hi @shathish-vsk ,
Simi-studio is generated from pwa-studio 3.0.0 which only works with Magento 2.3.1 and later version, please update your Magento version and try it again!

**Comment by bilalyaqoob** [comment]
I am getting the same error. Did you solved that? Please help me

**Comment by codynguyen1** [comment]
@bilalyaqoob  I'm sorry the issue got closed and I did not get notified about your message.
which branch of simi-studio and which backend of magento are your running with?
